version: '3.9'

services:
  app:
    image: tigrigna-quran-api
    container_name: app 
    command: ['npm', 'start']
    restart: always
    ports:
      - 4000:3000 
    environment:
      - CONNFIGURATION_NAME=dev_quran_db
      - DB_POSTGRES_CONNECTOR=postgresql
      - DB_POSTGRES_URL=postgresql+psycopg2://quran_user:S3cret@localhost:5432/quran_db
      - DB_POSTGRES_HOST=postgres
      - DB_POSTGRES_PORT=5432
      - DB_POSTGRES_USER=quran_user
      - DB_POSTGRES_PASSWORD=S3cret
      - DB_POSTGRES_DATABASE=quran_db
    depends_on:
      - postgres
    external_links:
      - postgres
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=quran_user
      - POSTGRES_DB=quran_db

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - '8888:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.com
      PGADMIN_DEFAULT_PASSWORD: test
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  postgres-data:
  pgadmin-data:
